@baseUrl = "http://localhost:8082"

# Create Profile 
POST {{baseUrl}}/profile
Content-Type: application/json

{
  "name": "Jean",
  "lastName": "Castro",
  "nickname": "jean.dev",
  "age": 28,
  "bio": "<p>Software developer apaixonado por Go.</p>",
  "pictureUrl": "https://example.com/profile.jpg",
  "userId": 123
}

